site_name: Waistline API Documentation
theme:
  name: material
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Dashboard: 'dashboard.md'
  - 'Synchronise your mobile app': 'synchronise.md'
  - 'API Documentation': 'api-documentation/index.md'
  - 'Data visualization': 'data-visualization.md'
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
