name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PWD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64 #,linux/arm64 # Too long building for arm on GitHub runners (will wait until the arm runners come to automate)
        build-args: VERSION=${{ secrets.PHP_VERSION }}
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/waistline-api:latest, ${{ secrets.CONTAINER_REGISTRY_URL }}/waistline-api:${{ secrets.VERSION }}
